name: JSTasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Dependencies
      run: swift package update
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
